# Generated by Django 3.2.3 on 2021-06-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyphotos',
            old_name='name',
            new_name='name_of_image',
        ),
        migrations.RenameField(
            model_name='pharmacyphotos',
            old_name='photos',
            new_name='pharmacy',
        ),
    ]
