# Generated by Django 3.2.3 on 2021-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='province',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='workplace',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
