# Generated by Django 3.2.3 on 2021-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210528_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reciever',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
