# Generated by Django 3.2.3 on 2021-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210528_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(default='wwer', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
