# Generated by Django 3.2.3 on 2021-05-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210528_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advatisements',
            new_name='Advatisement',
        ),
    ]
