# Generated by Django 3.2.3 on 2021-05-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_advatisements_advatisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advatisement',
            new_name='Advertisement',
        ),
    ]
